### ISSUE TITLE
Can't open the website http://konect.cc/

### ISSUE THREAD

**Issue by wzbxpy** [kunegis/konect-handbook#2]
It seems like the website hangs

**Comment by houchengbin** [comment]
I am having the same problem.

**Comment by jmon12** [comment]
Same here. Began indeed about three weeks ago I would say.

**Comment by kunegis** [comment]
Hello everyone -- Thanks for your interest in KONECT.  KONECT is switching to a subscription model, see details here:  https://raw.githubusercontent.com/kunegis/cv/master/overview.pdf
I'll be happy to answer more questions via email at <kunegis@gmail.com>

**Comment by YunMoZhang** [comment]
Hi @kunegis ,
KONECT is very helpful. Thank you for creating it. But this website (http://konect.cc) is not accessible these few days. And the document you mentioned about subscription model can't be opened. Could you please let me know the ways of accessing the datasets in KONECT now?

**Comment by CyanYuKi** [comment]
hi,@YunMoZhang Have you accessed to KONECT ?你成功连上了吗

**Comment by YunMoZhang** [comment]
not yet

**Comment by CyanYuKi** [comment]
@YunMoZhang It seems to be shut down with the state code 502 :( 
Now I don't know how to access to it.

**Comment by kunegis** [comment]
Hi everyone:  The site konect.cc is down permanently.  There is no way to access the data that was there.  This is because I'm not in academia anymore, and the University of Namur shut down the site.
Now, there would be a theoretical possibility to get the data back, and that would be to hire me for doing just that, but it would have to be at conditions at least as good as with my current employers, so unfortunately not that likely.
